# Generated by Django 4.2.1 on 2023-05-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingdoctors',
            name='address',
            field=models.CharField(default='unspecified', max_length=50, verbose_name='address'),
            preserve_default=False,
        ),
    ]
