# Generated by Django 4.2.1 on 2023-05-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pendingdoctors_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPharmacists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('First_name', models.CharField(max_length=50, verbose_name='First_name')),
                ('Last_name', models.CharField(max_length=50, verbose_name='Last_name')),
                ('Email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('phoneNumber', models.CharField(max_length=8, verbose_name='phone number')),
            ],
        ),
    ]
