# Generated by Django 4.2.1 on 2023-05-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pendingpharmacists'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingdoctors',
            name='password',
            field=models.CharField(default='123', max_length=100, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingpharmacists',
            name='password',
            field=models.CharField(default='123', max_length=100, verbose_name='password'),
            preserve_default=False,
        ),
    ]
