# Generated by Django 4.2.1 on 2023-05-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pendingdoctors_password_pendingpharmacists_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingdoctors',
            name='Specialty',
            field=models.CharField(max_length=50, verbose_name='Specialty'),
        ),
    ]
