# Generated by Django 4.2.1 on 2023-05-07 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_alter_pendingdoctors_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='actualPharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('phoneNumber', models.CharField(max_length=8, verbose_name='phone number')),
                ('username', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='actualDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialty', models.CharField(max_length=50, verbose_name='Specialty')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('phoneNumber', models.CharField(max_length=8, verbose_name='phone number')),
                ('username', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
