# Generated by Django 4.2.1 on 2023-05-07 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_actualpharmacist_actualdoctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualdoctors',
            name='username',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actualpharmacist',
            name='username',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacists', to=settings.AUTH_USER_MODEL),
        ),
    ]
