# Generated by Django 4.2.1 on 2023-05-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingDoctors',
        ),
    ]
