# Generated by Django 4.2.1 on 2023-05-07 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulingApp', '0002_delete_pendingdoctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usernameDestination', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingApp.medicament')),
                ('Ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligne', to='schedulingApp.ordonnance')),
            ],
        ),
    ]
