# Generated by Django 4.2.1 on 2023-05-07 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulingApp', '0004_alter_ordonnance_usernamedestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='Doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ligneordonnance',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='usernameDestination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userDestination', to=settings.AUTH_USER_MODEL),
        ),
    ]
