# Generated by Django 4.2.1 on 2023-05-07 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulingApp', '0007_ordonnance_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='Doctor',
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='usernameDestination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Destination', to=settings.AUTH_USER_MODEL),
        ),
    ]
