# Generated by Django 4.2.1 on 2023-05-08 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulingApp', '0009_ordonnance_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='etat',
            field=models.CharField(default='unsent', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserPendingOrdoannance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsersWaiting', to='schedulingApp.ordonnance')),
                ('usernameDestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PendingOrdonnancePatient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacistPendingOrdoannance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PharmacistOrdonnance', to='schedulingApp.ordonnance')),
                ('usernameDestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PendingOrdonnancePhrmacist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
