# Generated by Django 4.2.1 on 2023-05-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingApp', '0010_ordonnance_etat_userpendingordoannance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacistpendingordoannance',
            old_name='usernameDestination',
            new_name='Pharmaciste',
        ),
        migrations.RenameField(
            model_name='userpendingordoannance',
            old_name='usernameDestination',
            new_name='userWaiting',
        ),
    ]
