# Generated by Django 4.2.1 on 2023-05-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingApp', '0011_rename_usernamedestination_pharmacistpendingordoannance_pharmaciste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='decision',
            field=models.CharField(default='waiting', max_length=255),
            preserve_default=False,
        ),
    ]
