# Generated by Django 4.2.1 on 2023-05-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingApp', '0012_ordonnance_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='weight',
        ),
        migrations.AddField(
            model_name='medicament',
            name='list',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicament',
            name='prixPublic',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
