# Generated by Django 4.2.1 on 2023-05-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingApp', '0014_alter_medicament_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='date',
            field=models.DateField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
    ]
